### ISSUE TITLE
`map_coords_in_place` should allow the scalar typed to be mapped to a different scalar type

### ISSUE THREAD

**Issue by frewsxcv** [georust/geo#1221]
Current trait signature:

```rust
fn map_coords_in_place(&mut self, func: impl Fn(Coord<T>) -> Coord<T>) { ... }
```

Because this is going from `T` to `T`, this means we are unable to transform the scalar type (e.g. converting from `f64` to `f32`).

If we changed this from `T` to `U`, this could allow more flexibility and make it possible to change the scalar type.

**Comment by michaelkirk** [comment]
This is already possible with [`MapCoords`](https://github.com/georust/geo/blob/c975e976c807c9eb16f19987ab2559dec7853eea/geo/src/algorithm/map_coords.rs#L31)

It wouldn't make sense for `MapCoordsInPlace` because it's **In Place**. It's mutating the existing reference - you can't change the type... assuming you're not talking about `unsafe` or `transmute` or something?

**Comment by michaelkirk** [comment]
Also, I forgot about `Convert` - which does the same thing but *only* changes the type, (e.g. f64 -> f32) but no further transformation.

**Comment by frewsxcv** [comment]
Ooops you are totally right🤦🏻
