### ISSUE TITLE
Add `Point::from_dms` function and `Point::dms` method on a Point for constructing from degrees/minutes/seconds

### ISSUE THREAD

**Issue by frewsxcv** [georust/geo#298]
Would these be helpful?

Something like:

```rust
impl Point {
    pub fn from_dms(deg: i64, min: i64, sec: i64) -> Self { ... }

    pub fn dms(self) -> (i64, i64, i64) { ... }
}
```

**Comment by urschrei** [comment]
Hmm couldn't dms be from geodetic or geographic coordinates?

**Comment by frewsxcv** [comment]
This is a very overdue comment, but are you able to expand on the differences? Or any links to resources that explain the differences?

**Comment by frewsxcv** [comment]
Since my last comment, I have done some reading about geodesy. After reading [this section of a Wikipedia article](https://en.wikipedia.org/wiki/Geodetic_datum#Geodetic_coordinates), it seems like geodetic coordinates use “latitude (ϕ), longitude (λ), and height (h)”. Considering that, it seems like `dms` would imply geographic coordinates. Does this sound right? We mention in the docs that these methods are _not_ geodetic coordinates 🤷‍♂️

**Comment by urschrei** [comment]
I think what I was trying to get at is that if people see conversion functions from/to DMS, they might also assume that the algorithms will work correctly with those coordinates, which isn't the case (apart from the Haversine and Euclidean distance methods). But maybe I'm overthinking it, since you have to get your GPS coordinates (for example) into the system somehow before projecting them anyway.

**Comment by frewsxcv** [comment]
Closing this as I think @urschrei is right here, this could be confusing
