### ISSUE TITLE
Rect constructor should enforce (min.x < max.x) and (min.y < max.y)

### ISSUE THREAD

**Issue by frewsxcv** [georust/geo#359]
See `Use case 1` in https://github.com/georust/geo/issues/354

**Comment by rmanoka** [comment]
Please consider swapping the coords to enforce the constraint, rather than `panic`-ing if it is not true.

Use case: for instance, GDAL libraries use an inverted coord. system for the pixel vs world.  That is, pixel (0,0) is top-left of raster in accordance with usual CV notion, while the min in true world coords (such as long, lat or other projected coords) occurs at bottom-left of the raster.

It is intuitive to provide a point-wise transform function, which is expected to work on all shapes.  Unfortunately, it breaks down with `Rect` due to the aforementioned panic.

Can provide a PR if this makes sense to you.

**Comment by michaelkirk** [comment]
Looks like this was resolved with #360
