### ISSUE TITLE
Speed up algorithms with Rayon

### ISSUE THREAD

**Issue by frewsxcv** [georust/geo#363]
Tried this out in https://github.com/georust/geo/compare/frewsxcv-rayon?expand=1, but didn't see any significant performance improvements?

**Comment by urschrei** [comment]
Hm that's weird. Something like polygon area involving multiple inner rings would probably be a good candidate too.

**Comment by tsturzl** [comment]
Just a little input here. I've been using geo for some robotics path planning work. I also thought of using rayon for speed up since I have to check for intersections between many linestrings and polygons, but what I noticed is it was actually going noticable slower. I don't have any solid numbers or benchmarks for you, but I don't think the speed up of using something like rayon is going to be very impactful for anything other than very large objects with an incredibly high number of points. This is just my use case. 

If you look at the Rayon blog, their own benchmarks show that operations on an array of 1k length is actually slightly slower.

Another option to explore here is to support Rayon as an optional feature, but having tried something similar in a project not long ago I've noticed this make code harder to maintain as you often have to maintain 2 versions of the same thing.

Hope this input is helpful.
