### ISSUE TITLE
support no_std

### ISSUE THREAD

**Issue by brenzi** [georust/geo#422]
I'd like to use geo in a `no_std` build. Any chance this will be supported soon? If not on you roadmap, would you accept a PR?

**Comment by frewsxcv** [comment]
Many of geo's core geometry types incorporate heap allocated vectors, like [`LineString`](https://docs.rs/geo/0.12.2/geo/struct.LineString.html). Do you know how we'd work around this for `no_std`?

**Comment by brenzi** [comment]
This shouldn't be a problem, you could use 'core::vec::Vec' in that case.

**Comment by TeXitoi** [comment]
There is no Vec in core. If you want to target pure core, the simplest thing would be to not provide genotypes, but provide traits for geometries.

Another solution, simpler but more restrictive is to depend on alloc. But you need an allocator and I think using alloc is feature gated, so reserved to nightly. It would allow to support web assembly at least, and embedded with an allocator.

**Comment by urschrei** [comment]
> My targets would be both wasm and sgx. So using alloc is fine for me. nightly is fine too

Nightly is not an option for the `geo` crate, though, and I don't know whether you can easily feature-gate nightly features. In any case, if you feel like you have an idea of how to balance the various constraints discussed above, please feel free to open a proof of concept PR to drive the discussion forward!

**Comment by brenzi** [comment]
@urschrei alloc is stable now, so my PR uses alloc. However, now the dependency on rstar is still an issue as they don't support no_std yet...

**Comment by frewsxcv** [comment]
If / when https://github.com/Stoeoef/rstar/pull/27 merges, we can move forward with this. Thanks for making this change @brenzi! We should also make sure to add a no_std entry to our CI matrix https://github.com/georust/geo/blob/master/.travis.yml#L10-L18 to make sure this continues to work going forward

**Comment by frewsxcv** [comment]
If/when https://github.com/Stoeoef/rstar/pull/27 merges, we should reopen and review https://github.com/georust/geo/pull/426

**Comment by wucke13** [comment]
@frewsxcv That is most likely not going to happen, since https://github.com/georust/rstar/pull/83 was just merged :tada:. Since `rstar` is now `no_std`, maybe its time to reopen this issue?

On that behalf, I have a remark. For `rstar` we went down a feature-less way of implementing `no_std` support, by declaring the crate `no_std` while having it depend on `alloc`. My interest in `georust` is motivated by embedded platforms, which in part do not even support heap memory. Thus, I'd be in favor of having `georust` itself make the dependencies on `alloc` optional (for example by having a `std` feature and an `alloc` feature like serde for example), thus allowing for all heapless algorithms in `georust` to be used even without an allocator.

**Comment by wucke13** [comment]
@frewsxcv Do you mind sharing your opinion on the question stated above?

**Comment by frewsxcv** [comment]
As long as we have an extra job in our matrix that builds with `no_std`, and it's just adding some cfg flags, then that seems fine to me!
