### ISSUE TITLE
Should Rect constructor enforce non-zero width and height

### ISSUE THREAD

**Issue by frewsxcv** [georust/geo#441]
For reference, we currently have this check when we construct a `Rect`:

https://github.com/georust/geo/blob/a12767570cdf7760bb75171836be6802ef0e212d/geo-types/src/rect.rs#L109-L114

Should this instead be:

```rust
min.x < max.x && min.y < max.y
```

To enforce that a `Rect` has a positive width and height?

**Comment by michaelkirk** [comment]
Can you expound on your reasoning for disallowing zero-sized rects? Is it just that they "seem weird"?

It's true that it's a little strange, but my first impulse is that we should continue to allow zero-sized rects, since they can be useful as a sort of "unity" concept that composes well. For example, see [my comment here](https://github.com/georust/geo/pull/443#discussion_r415148075).

A brief unscientific survey of some other rectangle API's (geographic and graphics) didn't turn up zero-sized rects as being invalid.  

Some graphics frameworks explicitly allow it (https://developer.apple.com/documentation/coregraphics/cgrectzero), but most don't explicitly mention it.

**Comment by frewsxcv** [comment]
> Is it just that they "seem weird"?

honestly yeah haha. i saw this in the code and wasn't sure if it was intentional or not, so opened this to start the convo. i hadn't done any research, so thanks for looking into it 🙇

maybe as an action item then, we should document this behavior in the `Rect` docs, in case it catches people by surprise
