### ISSUE TITLE
Haversine length results appears to be incorrect?

### ISSUE THREAD

**Issue by leontoeides** [georust/geo#491]
let linestring = LineString::<f64>::from(vec![
        // 1600 Pennsylvania Ave NW, Washington, DC
        (38.898556, -77.037852),
        // 1922 F St NW, Washington, DC
        (38.897147, -77.043934),
    ]);
    let length = linestring.haversine_length();
    println!("Geo Haversine Distance: {} metres.", length);

Geo Haversine Distance: 677.1996056315458 metres.

Everything else comes out as:

https://andrew.hedges.name/experiments/haversine/
0.549 kilometres

https://www.vcalc.com/wiki/vCalc/Haversine+-+Distance
0.54915656696928 kilometres

Rust 'haversine' crate
549.1557912038085 metres

**Comment by urschrei** [comment]
I assume it's because we use a different mean earth radius (see #176 for the rationale) compared to the examples you cite (Hedges uses 6373 km, vCalc's is unstated and not obvious in the source). None of the measurements are necessarily wrong, since there isn't consensus about what constitutes the correct radius. In general, I would use Vincenty distance for cheap calculations like this: it's more accurate, and nobody disagrees about the values used to calculate it.

**Comment by leontoeides** [comment]
I attempted to search Github for this issue but I didn't find anything. Thanks so much for the response! I understand the difference now. I will also look into Vicenty. Interesting. Thanks again. Cheers!
