### ISSUE TITLE
Create Triangulate algorithm

### ISSUE THREAD

**Issue by frewsxcv** [georust/geo#568]
A new algorithm for triangulating geometries with areas.

```rust
pub trait Triangulate {
    fn triangulate(&self) -> Vec<Triangle>;
}

impl Triangulate for Polygon { ... }

impl Triangulate for MultiPolygon { ... }

impl Triangulate for Rect { ... }

impl Triangulate for Triangle { ... }
```

Thoughts:

- Should we have separate traits for different triangulation algorithms? e.g. ear clipping, Delaunay, Voronoi
- Should we have a separate trait method for returning triangle indices? This is what https://github.com/donbright/earcutr returns, for example
- If we decide to incorporate ear clipping, we can reuse my existing geo-types to earcutr code [here](https://github.com/frewsxcv/rgis/blob/fcfec49cdeb0c62b12b8d79ec44551f616f11d7c/rgis/src/main.rs#L45-L60) and [here](https://github.com/frewsxcv/bevy-earcutr/blob/master/src/lib.rs)

**Comment by michaelkirk** [comment]
I think this would be a good addition!

Some design thoughts:

> Should we have a separate trait method for returning triangle indices?

Do you mean _vertex_ indices? Otherwise I don't understand why an individual triangle would ever appear more than once.

I've only recently started doing any graphics programming, but the API I typically want is one which returns vertices and their indexes - something like:

```
pub trait Triangulate {
    // returns `(triangles, vertices)` where each `triangle` is represented by three indexes, corresponding to its corners 
    // in `vertices`
    fn triangulate(&self) -> (Vec<(usize, usize, usize)>, Vec<Coordinate>);
}
```

> ` fn triangulate(&self) -> Vec<Triangle>;`

Maybe better?: ` fn triangle_iter(&self) -> impl Iter<Item=Triangle<T>>`

If we have a compressed vertex representation (as above) this might be a slightly smaller and more flexible way to store things. I'm not familiar enough with how the underlying triangulation algorithms work to know if this is actually useful though — if they're just internally building up essentially a fully expanded list of triangles, then this doesn't get us anything meaningful.

**Comment by frewsxcv** [comment]
this is done:

https://docs.rs/geo/latest/geo/algorithm/triangulate_spade/trait.TriangulateSpade.html

https://docs.rs/geo/latest/geo/algorithm/triangulate_earcut/trait.TriangulateEarcut.html
