### ISSUE TITLE
Release geo 0.17.0

### ISSUE THREAD

**Issue by frewsxcv** [georust/geo#599]
Our changelog is starting to get big. Should we cut a new release? What else should we include?

**Comment by michaelkirk** [comment]
#600 is the only thing I wanted to sneak in. Otherwise, ready to ship IMO.

**Comment by frewsxcv** [comment]
```
error: failed to prepare local package for uploading

Caused by:
  failed to select a version for `geo-types`.
      ... required by package `geo v0.17.0 (/Users/coreyf/dev/georust/geo/geo)`
  versions that meet the requirements `^0.6.2` are: 0.6.2

  the package `geo` depends on `geo-types`, with features: `approx` but `geo-types` does not have these features.
   It has a required dependency with that name, but only optional dependencies can be used as features.


  failed to select a version for `geo-types` which could resolve this conflict
```

Just tried to release `geo` and got this error. Seems like we need to bump `geo-types` too, yeah? Are any of the things in the `geo-types` changelog breaking changes?

Note that I did push this commit: https://github.com/georust/geo/commit/8a6969395ea2023899b0432240d02743551afda3 but did not release yet.

**Comment by michaelkirk** [comment]
> Seems like we need to bump geo-types too, yeah? 

yep

> Are any of the things in the geo-types changelog breaking changes?

I didn't intend so, but looking again, I realize there is for a segment of people for which things could break.

Previously geo-types unconditionally included `approx`, but it was only actually used for the `rstar` integration. If people were previously using `geo-types` directly (not via `geo`) with the `rstar` feature enabled, they'll need to change to `use-rstar`, otherwise the rstar code which uses the approx crate will not compile. This won't affect people who use the `geo` crate which was updated to use the `use-rstar` feature.

A couple of options that occur to me:

1. we could include approx in the default features. This would still break for people building geo-types with `--no-default-features --features rstar`

2. we could once again make approx non-optional. The change would be a slightly larger geo-types binary -  everyone would get the new RelativeEq/AbsDiffEq traits

3. we could bump for a breaking change. If we do this, we should also include https://github.com/georust/geo/issues/597 to avoid an inevitable future bump.

**Comment by michaelkirk** [comment]
I think I prefer this approach: 

3. we could bump for a breaking change. If we do this, we should also include #597 to avoid an inevitable future bump.

Since we wanted to do it anyway. If we do, are there any other breaking geo-types changes to include?

**Comment by frewsxcv** [comment]
Yeah, geo-types breaking change sounds good. I'm a little busy today and tomorrow to help out with that, but some lingering thoughts:

- I reverted https://github.com/georust/geo/commit/8a6969395ea2023899b0432240d02743551afda3 on master. Didn't want to leave that around if we're not ready to bump
- We should consider copying the geo-types changes into the geo changelog
- +1 to including https://github.com/georust/geo/issues/597

**Comment by michaelkirk** [comment]
#602 (which addresses #597) is kind of a big one that I wanted to leave open for a few days in case affected people had feedback. 

Is getting geo-0.17 out urgent? If so, I'd recommend making `approx` once again mandatory, and only bumping geo-types with a patch bump since no API will be broken.

**Comment by michaelkirk** [comment]
(My preference would be to just wait a few days, but if you need this released sooner I'm happy to make it happen!)

**Comment by frewsxcv** [comment]
0.17.0 is now released
