### ISSUE TITLE
Combine `MapCoords` and `MapCoordsInplace` into `MapCoords`

### ISSUE THREAD

**Issue by frewsxcv** [georust/geo#721]
Similar to how `translate_inplace` exists on the `Translate` trait

**Comment by michaelkirk** [comment]
I took a pass at this, but it ended up being trickier than I expected. Maybe someone else has some idea:

With this trait definition:
```
pub trait MapCoords<T, NT> {
    type Output;

    fn map_coords(&self, func: impl Fn(&(T, T)) -> (NT, NT) + Copy) -> Self::Output
    where
        T: CoordNum,
        NT: CoordNum;

    fn try_map_coords<E>(
        &self,
        func: impl Fn(&(T, T)) -> Result<(NT, NT), E> + Copy,
    ) -> Result<Self::Output, E>
    where
        T: CoordNum,
        NT: CoordNum;

    fn map_coords_in_place(&mut self, func: impl Fn(&(T, T)) -> (T, T))
        where
            T: CoordNum;

    fn try_map_coords_inplace<E>(
        &mut self,
        func: impl Fn(&(T, T)) -> Result<(T, T), E>,
    ) -> Result<(), E>
        where
            T: CoordNum;
}
```

And this trait impl:
```
impl<T: CoordNum, NT: CoordNum> MapCoords<T, NT> for Point<T> {
    type Output = Point<NT>;

    fn map_coords(&self, func: impl Fn(&(T, T)) -> (NT, NT) + Copy) -> Point<NT>
    {
        let new_point = func(&(self.0.x, self.0.y));
        Point::new(new_point.0, new_point.1)
    }

    fn try_map_coords<E>(
        &self,
        func: impl Fn(&(T, T)) -> Result<(NT, NT), E>,
    ) -> Result<Point<NT>, E>
        where
        NT: CoordNum
    {
        let new_point = func(&(self.0.x, self.0.y))?;
        Ok(Point::new(new_point.0, new_point.1))
    }

    fn map_coords_in_place(&mut self, func: impl Fn(&(T, T)) -> (T, T))
    {
        let new_point = func(&(self.0.x, self.0.y));
        self.0.x = new_point.0;
        self.0.y = new_point.1;
    }

    fn try_map_coords_inplace<E>(
        &mut self,
        func: impl Fn(&(T, T)) -> Result<(T, T), E>,
    ) -> Result<(), E>
        where
            T: CoordNum {
        let new_point = func(&(self.0.x, self.0.y))?;
        self.0.x = new_point.0;
        self.0.y = new_point.1;

        Ok(())
    }
}
```

But this fails to compile:
```
let mut point = Point::new(1., 2.);
point.map_coords_in_place(|(x, y)| (x * 2.0, y * 2.0) );
      ^^^^^^^^^^^^^^^^^^^ cannot infer type for type parameter `NT` declared on the trait `MapCoords`
```

Basically - in this case, `NT` doesn't matter since it's not used in the method, so the compiler doesn't know which implementation to use.

This succeeds:
```
MapCoords::<f64, f64>::map_coords_in_place(&mut point, |(x, y)| (x * 2.0, y * 2.0) );
```

as does:
```
MapCoords::<f64, i32>::map_coords_in_place(&mut point, |(x, y)| (x * 2.0, y * 2.0));
```

But no one wants to write that. I can't think of a way to handle this that's better than the current situation, where this method lives in a separate trait with only one type param.

**Comment by michaelkirk** [comment]
After reading a little bit more about generic default type params, it seems like the benefit is that you can omit them from your impl blocks. 

But we can't do that because we want our implementation to be generic based on NT.

e.g. we can indeed do something like this:

```
/// Map a function over all the coordinates in an object, returning a new one
pub trait MapCoords<T, NT = T> {    
    type Output;
    ....
}
```

But if we want to support generic outputs, our impl block needs to look like this:
```
impl<T: CoordNum, NT: CoordNum> MapCoords<T, NT> for Point<T> {
    type Output = Point<NT>;
    ...
}
```

Which induces the same compiler error.

I think we could avoid the compiler error with an impl block like this:
```
impl<T: CoordNum> MapCoords<T> for Point<T> {
    type Output = Point<T>;
    ...
}
```

But that precludes us from mismatching T and NT, so we couldn't map_coords a Geometry<f32> to a Geometry<f64>.

**Comment by michaelkirk** [comment]
Some ways forward:

1. do nothing.
2. consolidate from 4 traits into two traits, something like:
```
trait MapCoords<T, NT> {
   fn map_coords(fn((T,T)) -> (NT,NT)) -> Self::Output;
   fn try_map_coords<E>(fn((T,T)) -> Result<(NT, NT), E>)) -> Result<Self::Output, E>
}

trait MapCoordsInPlace<T> {
   fn map_coords_in_place(fn((T,T)) -> (T,T))
   fn try_map_coords<E>(fn((T,T)) -> Result<(T, T)>)) -> Result<(),E)
}
```

3. consolidate everything into one trait, but don't allow using Map coords for converting `Geometry<f32> -> Geometry<f64>`, do that in a different trait.

**Comment by frewsxcv** [comment]
Thanks for doing this investigation @michaelkirk. Consolidating into two is an improvement over having four, in my opinion

**Comment by michaelkirk** [comment]
Because of the hangups mentioned here: https://github.com/georust/geo/issues/721#issuecomment-1100391978, I believe this is as good as we can do.

Please reopen if I'm mistaken.
