### ISSUE TITLE
Replace MapCoords tuple parameter in function argument with a Coodinate parameter

### ISSUE THREAD

**Issue by frewsxcv** [georust/geo#804]
https://github.com/georust/geo/pull/800#discussion_r849490674

**Comment by michaelkirk** [comment]
Since the next release is breaking MapCoords (https://github.com/georust/geo/pull/810) we should consider doing this before the next release to avoid having to breaking it in two releases.

I assigned it to the 0.21.0 milestone - not unilaterally mandating that we have to do it, but just so we don't forget to consider it.

**Comment by michaelkirk** [comment]
Also, since we can convert a (T,T) to a coord, we *might* consider a non-breaking approach to this with a trait impl like:

```
    pub trait MapCoords<T: CoordNum, NT: CoordNum = T, OldCoord: Into<Coordinate<T>> = Coordinate<T>, NewCoord: Into<Coordinate<NT>> = Coordinate<NT>> {
```

Phew. It's kind of a mouthful though. Generics with defaults are a hell of a drug. I wonder what the error messages would look like, or if we'd be better off just making a clean break with a simple impl.

**Comment by urschrei** [comment]
> Also, since we can convert a (T,T) to a coord, we *might* consider a non-breaking approach to this with a trait impl like:
> 
> 
> 
> ```
> 
>     pub trait MapCoords<T: CoordNum, NT: CoordNum = T, OldCoord: Into<Coordinate<T>> = Coordinate<T>, NewCoord: Into<Coordinate<NT>> = Coordinate<NT>> {
> 
> ```
> 
> 
> 
> Phew. It's kind of a mouthful though. Generics with defaults are a hell of a drug. I wonder what the error messages would look like, or if we'd be better off just making a clean break with a simple impl.

It's long, but it's also self-explanatory / not cognitively complex, imo. I guess we'd have to have a look at the error message.

**Comment by frewsxcv** [comment]
My vote is to fully migrate to `Coordinate` without without `Into`. It should be a painless migration for users of `geo` who upgrade. That said I'm satisfied with the `Into<Coordinate>` idea too.
