### ISSUE TITLE
What's the support for real word geographic data?

### ISSUE THREAD

**Issue by Zizico2** [georust/geo#902]
Is there any way to wrap longitudes around [-180 to 180] (same for latitude)? And for "within" checks to take that wrapping into account. A point might not be inside a rectangle if the wrapping isn't taken into account but might be inside if it is. I'm asking for support for spherical coordinates I guess. Defining a `Rect` by its max and min coordinates doesn't work in spherical coordinates, which is what `geo` currently does. `gpx` validates coordinates but then uses `geo-types` for everything else so it inherits the same problems (?).

**Comment by urschrei** [comment]
Except where it's explicitly called out (e.g. Haversine), geo expects Euclidean coordinates, and operates in R2 (the real plane). This is evident from the Point and Coordinate docs, which both explicitly note that they operate in 2D space:

https://docs.rs/geo/latest/geo/geometry/struct.Coordinate.html

https://docs.rs/geo/latest/geo/geometry/struct.Point.html

GPX has checks because the spec mandates WGS84 coordinates, but those aren't spherical either.

There are bindings to S2 available in Rust (https://github.com/yjh0502/rust-s2), but fundamentally, geo and its ecosystem is Euclidean.

**Comment by Zizico2** [comment]
Thanks for the clarification!
closing

**Comment by lnicola** [comment]
It's also worth mentioning that some Rust GEOS and GDAL bindings are actually available.
