### ISSUE TITLE
geo-types CI is failing

### ISSUE THREAD

**Issue by rmanoka** [georust/geo#910]
Relevant logs:

```
   Compiling arbitrary v1.1.6
error[E0658]: use of unstable library feature 'array_from_fn'
   --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/arbitrary-1.1.6/src/lib.rs:655:36
    |
655 |         crate::size_hint::and_all(&array::from_fn::<_, N, _>(|_| {
    |                                    ^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #89379 <https://github.com/rust-lang/rust/issues/89379> for more information

error[E0747]: constant provided when a type was expected
   --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/arbitrary-1.1.6/src/lib.rs:655:56
    |
655 |         crate::size_hint::and_all(&array::from_fn::<_, N, _>(|_| {
    |                                                        ^
```
 
Any ideas on the reason?

**Comment by urschrei** [comment]
Stabilised in 1.63: https://doc.rust-lang.org/nightly/core/array/fn.from_fn.html
Added to arbitrary last month: https://github.com/rust-fuzz/arbitrary/blame/a2db1d0e6b88f40ff22bf2597ad0b62fff934ecc/src/lib.rs#L655 (see blame), so it's been in Arbitrary since 1.1.4 (released 29th of August).

So we'll have to bump [our CI and MSRV](https://github.com/georust/geo/blob/main/.github/workflows/test.yml#L69-L73) to 1.63 in `geo` and `proj`?

**Comment by frewsxcv** [comment]
We can also pin arbitrary to `1.1.5`

**Comment by urschrei** [comment]
> We can also pin arbitrary to `1.1.3`, or whatever the last version is that doesn't have it

Yeah, that might be quicker for now.

**Comment by rmanoka** [comment]
Awesome!  Thanks for the quick fix!
